Mobile layout
rusefi/msqur pull request #7
Opened 2020-09-08 05:45 UTC by ksmola

First step towards being more mobile friendly...

![Screenshot_20200907-223635_Firefox](https://user-images.githubusercontent.com/7853547/92437477-8bbc8e00-f196-11ea-9de5-bf578be81f35.png)

2020-09-08 11:19 UTC, rusefillc reviewed
fyi @andreika-git

2020-09-11 09:49 UTC, rusefillc commented
@ksmola poke - @andreika-git is waiting for the span clarifcation

2020-09-11 14:44 UTC, ksmola commented
What span are we talking about? I can't see his comment?

2020-09-11 14:47 UTC, rusefillc commented
@ksmola 

![image](https://user-images.githubusercontent.com/48498823/92939802-3abdcb80-f41c-11ea-9bc4-cd8ac018ce7f.png)

2020-09-11 14:48 UTC, rusefillc commented
@andreika-git I wonder if that's a "pending" comment which you have not published yet? you need to finish review for the comment to be visible or something?

2020-09-11 14:57 UTC, ksmola commented
Yeah i cant see that. Either way the span can get removed must be some testing/old code relict.

2020-09-11 15:19 UTC, andreika-git requested changes

2020-09-11 15:19 UTC, andreika-git commented on src/view/header.php
> +		<!-- <span>
Why do we need this span (commented out)?

2020-09-16 06:33 UTC, merged